#!/bin/sh
 
#define default return code as 0
rc=0

#curl local host - 200 code is "ok" 
#variable cfg.server.port so port can be dynamic in health check
STATUS=$(curl -s -o /dev/null -w '%{http_code}' http://localhost:{{cfg.server.port}}/sample/)

case $STATUS in
  200)
    rc=0 ;;
  1)
    rc=1 ;;
  2)
    rc=2 ;;
  *)
    rc=3 ;;
esac

# hab error codes 
# 0- ok
# 1- warning
# 2- critical
# 3- unknown

exit $rc
