#!/bin/sh
 
#define default return code as 0
rc=0

STATUS=$(curl -s -o /dev/null -w '%{http_code}' http://localhost:8080/sample/)

case $STATUS in
  1)
    rc=1 ;;
  200)
    rc=0 ;;
  4)
    rc=2 ;;
  *)
    rc=3 ;;
esac
 
exit $rc